#ifndef M_DATABASEDRIVERS_H
#define M_DATABASEDRIVERS_H

#define SQLITE_VERSION_3_DRIVER "QSQLITE"
#define SQLITE_VERSION_2_DRIVER "QSQLITE2"
#define POSTGRESQL_DRIVER "QPSQL"
#define MYSQL_DRIVER "QMYSQL"
#define ODBC_MSSQL_DRIVER "QODBC"

#endif // M_DATABASEDRIVERS_H
